#Site settings
title: zzh's blog
email:
description: Learner | Practitioner
baseurl: ""

url: ""
github_username:  zihaozhihao

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
